from google import genai
from config.settings import Settings

def llmcall(prompt):
    """Dispatches a text prompt to the Gemini API using the official Google GenAI client.

    Initializes the required system settings to retrieve the active Gemini API key, 
    instantiates the orchestration client, and transmits the provided text prompt payload 
    to the designated flash-lite model. Once the completion completes, it extracts and 
    returns the raw string text response.

    Args:
        prompt (str): The text instruction or prompt payload intended for model interpretation.

    Returns:
        str: The raw textual response block generated by the model.
    """
    settings = Settings()
    api_key = settings.GEMINI_API_KEY
    client = genai.Client(api_key=api_key)
    response = client.models.generate_content(
        model="gemini-2.5-flash-lite",
        contents={"text": prompt}
    )

    return (response.text)
